// Test definitions. Do NOT edit this file!

#include <string>

#define CATCH_CONFIG_MAIN // defines main() automatically
#include <catch2/catch.hpp>

#include "../ejercicio1.hpp"
#include "../ejercicio3.hpp"
#include "../ejercicio7.hpp"
#include "../ejercicio8.hpp"


// =====================
// tests for exercise 1
// ---------------------

TEST_CASE("Ex1", "[Ejercicio-1 OperaNumeros]")
{
    INFO("FUNCIONALIDAD ESPERADA: Se espera que tu programación sea capaz de sumar, restar y multiplicar dos números dobles según el operador indicado.");
    INFO("PROGRAMACIÓN: Funciones: double suma(double, double), double resta(double, double), double multiplica(double, double). Cada función debe recibir dos parámetros de tipo double y retornar el resultado correspondiente.");
    INFO("SUGERENCIA DE PROGRAMACIÓN: Implementa cada función para recibir dos parámetros de tipo double y retornar el resultado usando el operador aritmético adecuado (+, -, *). Verifica que los nombres y tipos coincidan exactamente con los requeridos.");
    
    REQUIRE(suma(11,43)==54);
    REQUIRE(resta(34,21)==13);
    REQUIRE(multiplica(15, 16)==240);
}

// =====================
// tests for exercise 3
// ---------------------

TEST_CASE("Ex3", "[Ejercicio-3 Suma pares entre 0 y 100]")
{
    INFO("FUNCIONALIDAD ESPERADA: Se espera que tu programación sume todos los números enteros pares entre 0 y 100 (incluyendo ambos).");
    INFO("PROGRAMACIÓN: Función: int sumaPares(void). La función no recibe parámetros y debe retornar la suma de los números pares en el rango especificado.");
    INFO("SUGERENCIA DE PROGRAMACIÓN: Utiliza un ciclo para recorrer los números del 0 al 100 y suma solo aquellos que sean pares (usa el operador % para verificar si un número es par).");
    
    REQUIRE(sumaPares()==2550);
}

// =====================
// tests for exercise 7
// ---------------------

TEST_CASE("Ex7", "[Ejercicio-7 Serie armonica]")
{
    INFO("FUNCIONALIDAD ESPERADA: Se espera que tu programación calcule la suma de los términos de una progresión aritmética, mostrando cada término y el valor total.");
    INFO("PROGRAMACIÓN: Función: int serieArmonica(int a, int d, int n). Debe recibir tres enteros: el primer término (a), la diferencia (d) y la cantidad de términos (n), y retornar la suma total.");
    INFO("SUGERENCIA DE PROGRAMACIÓN: Usa un ciclo para calcular cada término de la serie (a + i*d) y acumula la suma. Muestra cada término y el total usando cout.");
    
    REQUIRE(serieArmonica(1, 3, 25) == 925);
    REQUIRE(serieArmonica(2, 5, 10) == 245);
}

// =====================
// tests for exercise 8
// ---------------------

TEST_CASE("Ex8", "[Ejercicio-8 Medias geometrica y armonica]")
{
    INFO("FUNCIONALIDAD ESPERADA: Se espera que tu programación calcule la media geométrica y la media armónica de los números del 1 al N.");
    INFO("PROGRAMACIÓN: Funciones: double mediaGeometrica(int), double mediaArmonica(int). Cada función debe recibir un entero N y retornar el valor correspondiente.");
    INFO("SUGERENCIA DE PROGRAMACIÓN: Para la media geométrica, multiplica todos los números del 1 al N y calcula la raíz N-ésima. Para la media armónica, suma los recíprocos de los números del 1 al N y divide N entre esa suma.");
    
    REQUIRE(std::to_string(mediaGeometrica(3))=="1.817121");
    REQUIRE(std::to_string(mediaArmonica(3))=="1.636364");
}